name: lint-test-cover-docs
on:
  push:
    branches:
      - '**'
  workflow_call: # If invoked by build-publish-sign-release workflow.
jobs:
  lint_test_cover_docs:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Python.
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Lint and test module.
        run: |
          pip install -U .[lint,test]
          python -m pylint egcd # Check against linting rules.
          python -m pytest # Run tests.
          python src/egcd/egcd.py -v # Run tests via execution.
      - name: Publish coverage results.
        run: |
          pip install -U .[coveralls]
          python -m coveralls --service=github # Submit to coveralls.
        if: matrix.python-version == '3.12'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Test auto-generation of documentation.
        run: |
          pip install -U .[docs]
          cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. && make html && cd ..
